"""Synthetic labels, for exercising the evaluation pipeline before any human has labelled.

[pandas] Nothing here imports Polars or `ingest`.

WHAT THESE ARE NOT
------------------
These are not ground truth and the numbers computed from them are not accuracy. They
exist so that `labeling.evaluate` can be run, tested and debugged while the real label
file is empty.

Every record is written with `synthetic: true` and `annotator: "SYNTHETIC"`, they are
written to a separate file by default, and `labeling.evaluate` refuses to print a metric
from them without saying on the same line that it is synthetic.

The generator deliberately does **not** simply copy the model's own verdict. If it did,
precision and recall would come out at 1.0 by construction and the pipeline would look
correct while proving nothing. Instead it starts from the model's ranking and injects a
fixed number of disagreements, so the metrics have something to measure.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from labeling import store
from labeling.sampling import DEFAULT_SEED, build_queue
from lakehouse.paths import REPO_ROOT

SYNTHETIC_PATH = REPO_ROOT / "labeling" / "decisions.synthetic.jsonl"

# How much the synthetic labeller disagrees with the model, by stratum. Chosen to give
# the evaluation something non-trivial to report, not to model any real error rate.
DISAGREEMENT_RATE = {
    "ambiguous": 0.5,
    "contested": 0.4,
    "cook_county": 0.1,
    "high_confidence": 0.1,
    "low_confidence": 0.05,
}

UNSURE_RATE = 0.05


def generate(
    queue: pd.DataFrame | None = None,
    seed: int = DEFAULT_SEED,
    path: Path | None = None,
    reveal_probability: bool = False,
) -> Path:
    """Write a synthetic decision for every pair in the queue.

    `reveal_probability` mimics a labeller who had the model's opinion on screen; it
    only affects what is recorded in `probability_shown`, never the verdict.
    """
    pairs = queue if queue is not None else build_queue(seed=seed)
    target = Path(path or SYNTHETIC_PATH)
    if target.exists():
        target.unlink()

    rng = np.random.default_rng(seed)
    for _, row in pairs.iterrows():
        stratum = str(row.get("stratum", "low_confidence"))
        model_says_match = float(row["match_probability"]) >= 0.5
        if rng.random() < UNSURE_RATE:
            verdict = "unsure"
        else:
            disagrees = rng.random() < DISAGREEMENT_RATE.get(stratum, 0.1)
            agrees_with_model = model_says_match != disagrees
            verdict = "match" if agrees_with_model else "no_match"
        store.append(
            store.Decision(
                pair_id=row["pair_id"],
                unique_id_l=str(row["unique_id_l"]),
                unique_id_r=str(row["unique_id_r"]),
                verdict=verdict,
                annotator=store.SYNTHETIC_ANNOTATOR,
                probability_shown=(float(row["match_probability"]) if reveal_probability else None),
                stratum=stratum,
                queue_seed=int(row.get("queue_seed", seed)),
                notes="generated by labeling.synthetic; not ground truth",
                synthetic=True,
            ),
            path=target,
        )
    return target


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Write synthetic labels (NOT ground truth).")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--reveal-probability", action="store_true")
    args = parser.parse_args(argv)
    path = generate(seed=args.seed, reveal_probability=args.reveal_probability)
    counts = store.summary(path)
    print(f"wrote {counts['lines_written']} SYNTHETIC decisions to {path}")
    print(f"verdicts: {counts['verdicts']}")
    print("These are not ground truth. Any metric computed from them is not accuracy.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
