"""Measure what the model does: blocking reach, calibration, and per-comparator weights.

[pandas] Nothing here imports Polars or `ingest`.

The per-comparator table is the important output. It is what says which evidence is
actually doing the work, and it is the only honest way to answer "why did this pair
score what it scored".
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd
import pyarrow as pa

from lakehouse.catalog import write_table
from lakehouse.paths import RESOLUTION_NAMESPACE
from resolution.model import TrainedModel, train

MATCH_TABLE = "gspt_plantgen_candidates"

# The two most crowded counties in PLANTGEN, and they behave completely differently.
# Allegheny (Pittsburgh) has 9 plants and 9 distinct ZIPs, so ZIP fully separates them.
# Cook (Chicago) has 10 plants but only 7 distinct ZIPs and one plant with no ZIP at
# all -- county and ZIP fail *together* there. An average over all shared-county plants
# hides that, so Cook is reported on its own.
WATCHED_COUNTIES = {"17031": "Cook IL (Chicago)", "42003": "Allegheny PA (Pittsburgh)"}

QUANTILES = (0.5, 0.75, 0.9, 0.95, 0.99, 1.0)


# --------------------------------------------------------------------------------------
# 1. blocking
# --------------------------------------------------------------------------------------


@dataclass(frozen=True)
class BlockingReport:
    left_records: int
    right_records: int
    cartesian_pairs: int
    blocked_pairs: int
    fallback_records: int
    fallback_pairs: int

    @property
    def reduction_ratio(self) -> float:
        """Share of the full cross join that blocking removed.

        `blocked_pairs` already includes the pairs generated by the fallback rule for
        records no blocking key could reach. Excluding them would flatter the ratio by
        pretending the hardest records do not exist.
        """
        return 1 - (self.blocked_pairs / self.cartesian_pairs)

    def render(self) -> str:
        return "\n".join(
            [
                "1. Blocking",
                "-" * 68,
                f"  GSPT records                                 {self.left_records:>7d}",
                f"  PLANTGEN records                             {self.right_records:>7d}",
                f"  full cross join                              {self.cartesian_pairs:>7d}",
                f"  candidate pairs after blocking               {self.blocked_pairs:>7d}",
                f"    of which from the no-key fallback          {self.fallback_pairs:>7d}"
                f"   ({self.fallback_records} records with no blocking key)",
                f"  reduction ratio (fallback included)          {self.reduction_ratio:>7.4f}",
            ]
        )


def blocking_report(model: TrainedModel) -> BlockingReport:
    left, right = model.gspt, model.plantgen
    fallback_left = int((~left["has_blocking_key"]).sum())
    fallback_right = int((~right["has_blocking_key"]).sum())
    # Every no-key record on either side is paired with the whole of the other side.
    fallback_pairs = fallback_left * len(right) + fallback_right * len(left)
    fallback_pairs -= fallback_left * fallback_right
    return BlockingReport(
        left_records=len(left),
        right_records=len(right),
        cartesian_pairs=len(left) * len(right),
        blocked_pairs=len(model.predictions),
        fallback_records=fallback_left + fallback_right,
        fallback_pairs=fallback_pairs,
    )


# --------------------------------------------------------------------------------------
# 2 & 4 & 5. probability distributions
# --------------------------------------------------------------------------------------


def _quantiles(values: pd.Series) -> dict[str, float]:
    if values.empty:
        return {}
    out = {f"p{int(q * 100)}": float(values.quantile(q)) for q in QUANTILES}
    out["n"] = int(len(values))
    out["max"] = float(values.max())
    return out


def probability_histogram(
    predictions: pd.DataFrame, edges: tuple[float, ...] = (0.0, 0.01, 0.1, 0.5, 0.9, 0.99, 1.01)
) -> pd.DataFrame:
    """Bucketed counts of pairwise match probability."""
    labels = [f"[{edges[i]:g}, {edges[i + 1]:g})" for i in range(len(edges) - 1)]
    buckets = pd.cut(predictions["match_probability"], bins=list(edges), right=False, labels=labels)
    counts = buckets.value_counts().reindex(labels).fillna(0).astype(int)
    return counts.rename_axis("match_probability").reset_index(name="pairs")


def best_per_record(predictions: pd.DataFrame, side: str) -> pd.DataFrame:
    """Highest-scoring candidate for each record on one side.

    Splink emits `unique_id_l` / `unique_id_r`; which side is which is fixed by the
    order the frames were given to the Linker.
    """
    key = "unique_id_l" if side == "gspt" else "unique_id_r"
    ordered = predictions.sort_values("match_probability", ascending=False)
    return ordered.groupby(key, as_index=False).first()


# --------------------------------------------------------------------------------------
# 3. per-comparator weights
# --------------------------------------------------------------------------------------


# Below this many candidate pairs, an EM estimate is arithmetic rather than evidence.
LOW_SUPPORT_PAIRS = 10


@dataclass
class ComparatorRow:
    comparison: str
    level: str
    m: float | None
    u: float | None
    pairs: int = 0
    # Splink's null level carries no weight by design: it means "no evidence either
    # way", not "unestimated". It must not be reported as a failed estimate.
    is_null: bool = False

    @property
    def low_support(self) -> bool:
        """Estimated, but from too few pairs to be believed."""
        return self.estimated and 0 < self.pairs < LOW_SUPPORT_PAIRS

    @property
    def bayes_factor(self) -> float | None:
        if self.m is None or self.u in (None, 0):
            return None
        return self.m / self.u

    @property
    def match_weight(self) -> float | None:
        factor = self.bayes_factor
        if factor is None or factor <= 0:
            return None
        return math.log2(factor)

    @property
    def estimated(self) -> bool:
        return self.m is not None and self.u is not None


@dataclass
class ComparatorReport:
    rows: list[ComparatorRow] = field(default_factory=list)

    @property
    def unestimated(self) -> list[ComparatorRow]:
        """Levels EM could not estimate. Reported, never filled in with a guess."""
        return [r for r in self.rows if not r.estimated and not r.is_null]

    def as_frame(self) -> pd.DataFrame:
        return pd.DataFrame(
            [
                {
                    "comparison": r.comparison,
                    "level": r.level,
                    "m": r.m,
                    "u": r.u,
                    "bayes_factor": r.bayes_factor,
                    "match_weight": r.match_weight,
                }
                for r in self.rows
            ]
        )

    def render(self) -> str:
        lines = [
            "3. Comparator weights, estimated by EM",
            "-" * 68,
            f"  {'comparison':<12s} {'level':<20s} {'pairs':>6s} {'m':>9s} {'u':>9s}"
            f" {'BF':>9s} {'weight':>7s}",
        ]
        for row in self.rows:
            if row.is_null:
                lines.append(
                    f"  {row.comparison:<12s} {'(null: no evidence)':<20s} {row.pairs:>6d}"
                    f" {'--':>9s} {'--':>9s} {'--':>9s} {'0.00':>7s}"
                )
                continue
            m = f"{row.m:.6f}" if row.m is not None else "     --"
            u = f"{row.u:.6f}" if row.u is not None else "     --"
            factor = f"{row.bayes_factor:.1f}" if row.bayes_factor is not None else "--"
            weight = f"{row.match_weight:.2f}" if row.match_weight is not None else "--"
            flag = "  <-- low support" if row.low_support else ""
            lines.append(
                f"  {row.comparison:<12s} {row.level[:20]:<20s} {row.pairs:>6d}"
                f" {m:>9s} {u:>9s} {factor:>9s} {weight:>7s}{flag}"
            )
        if self.unestimated:
            lines += [
                "",
                "  NOT ESTIMABLE -- left unset rather than guessed. Every one of these is a",
                "  level that zero candidate pairs fell into, so there was nothing to learn from:",
            ]
            for row in self.unestimated:
                missing = ", ".join(
                    part for part, value in (("m", row.m), ("u", row.u)) if value is None
                )
                lines.append(
                    f"    {row.comparison}.{row.level}  ({row.pairs} pairs, missing {missing})"
                )
        low = [r for r in self.rows if r.low_support]
        if low:
            lines += [
                "",
                f"  LOW SUPPORT -- estimated from fewer than {LOW_SUPPORT_PAIRS} pairs. The number",
                "  exists but should not be relied on:",
            ]
            for row in low:
                lines.append(
                    f"    {row.comparison}.{row.level}  ({row.pairs} pairs, "
                    f"weight {row.match_weight:.2f})"
                )
        return "\n".join(lines)


def _gamma_values(levels: list[dict]) -> list[tuple[dict, int]]:
    """Pair each comparison level with the gamma value Splink will emit for it.

    The saved model JSON does not carry the value, so it is reconstructed the way
    Splink assigns it: the null level is -1, and the remaining levels count *down* from
    the most specific to the ELSE level at 0.
    """
    non_null = [level for level in levels if not level.get("is_null_level")]
    top = len(non_null) - 1
    out: list[tuple[dict, int]] = []
    index = 0
    for level in levels:
        if level.get("is_null_level"):
            out.append((level, -1))
        else:
            out.append((level, top - index))
            index += 1
    return out


def comparator_report(model: TrainedModel) -> ComparatorReport:
    """Per-level m, u, Bayes factor and weight, with the pair count each rests on.

    The pair count is not decoration. A level with a large weight and three supporting
    pairs is a different object from one with the same weight and three hundred, and the
    table is useless for judging evidence unless both are visible.
    """
    settings = model.linker.misc.save_model_to_json()
    predictions = model.predictions
    rows: list[ComparatorRow] = []
    for comparison in settings["comparisons"]:
        name = comparison["output_column_name"]
        gamma = f"gamma_{name}"
        occupancy = (
            predictions[gamma].value_counts().to_dict() if gamma in predictions.columns else {}
        )
        for level, value in _gamma_values(comparison["comparison_levels"]):
            rows.append(
                ComparatorRow(
                    comparison=name,
                    level=str(level.get("label_for_charts", "?")),
                    m=level.get("m_probability"),
                    u=level.get("u_probability"),
                    pairs=int(occupancy.get(value, 0)),
                    is_null=bool(level.get("is_null_level", False)),
                )
            )
    return ComparatorReport(rows=rows)


# --------------------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------------------


@dataclass
class ResolutionReport:
    blocking: BlockingReport
    comparators: ComparatorReport
    histogram: pd.DataFrame
    overall_quantiles: dict[str, float]
    by_county_crowding: pd.DataFrame
    watched_counties: pd.DataFrame
    canada: pd.DataFrame
    em_sessions: list[str]
    em_failures: list[str]

    def render(self) -> str:
        parts = [self.blocking.render(), ""]
        parts += [
            "2. Pairwise match probability",
            "-" * 68,
            self.histogram.to_string(index=False),
            "",
            "  quantiles over all candidate pairs: "
            + ", ".join(f"{k}={v:.4g}" for k, v in self.overall_quantiles.items()),
            "",
            self.comparators.render(),
            "",
            "4. Best match per PLANTGEN plant, by how crowded its county is",
            "-" * 68,
            self.by_county_crowding.to_string(index=False),
            "",
            "4b. The two most crowded counties, which do NOT behave alike",
            "-" * 68,
            "   Averaging over all shared-county plants hides this: ZIP rescues",
            "   Pittsburgh completely and does not rescue Chicago at all.",
            self.watched_counties.to_string(index=False),
            "",
            "5. Canadian GSPT plants (PLANTGEN is a US census: no counterpart exists)",
            "   Kept in the denominator on purpose. Dropping them in staging would shrink",
            "   the denominator and make the match rate look better than it is.",
            "-" * 68,
            self.canada.to_string(index=False),
        ]
        if self.em_failures:
            parts += ["", "EM passes that failed:", *[f"  {f}" for f in self.em_failures]]
        return "\n".join(parts)


def _watched_county_report(merged: pd.DataFrame, plantgen: pd.DataFrame) -> pd.DataFrame:
    """Per-county detail for the counties where blocking is weakest.

    ZIP is the evidence that is supposed to rescue a shared county. Whether it can is a
    property of the individual county, not of "shared counties" as a class, so the ZIP
    cardinality is reported next to the match outcome.
    """
    zips = plantgen.set_index("unique_id")["zip5"]
    rows = []
    for fips, label in sorted(WATCHED_COUNTIES.items()):
        members = merged[merged["county_fips"] == fips]
        member_zips = zips.reindex(members["unique_id"])
        rows.append(
            {
                "county": label,
                "plants": int(len(members)),
                "with_zip": int(member_zips.notna().sum()),
                "distinct_zips": int(member_zips.nunique(dropna=True)),
                "zip_separates_all": bool(
                    member_zips.notna().all() and member_zips.nunique(dropna=True) == len(members)
                ),
                "best_above_0_9": int((members["match_probability"] > 0.9).sum()),
                "best_above_0_5": int((members["match_probability"] > 0.5).sum()),
            }
        )
    return pd.DataFrame(rows)


def build(
    db_path: Path | None = None,
    warehouse: Path | None = None,
    model: TrainedModel | None = None,
    write: bool = True,
) -> tuple[TrainedModel, ResolutionReport]:
    """Train (or reuse) the model and produce every acceptance measurement."""
    trained = model if model is not None else train(db_path, warehouse)
    predictions = trained.predictions

    # PLANTGEN-side view: does a shared county leave the model anything to work with?
    plantgen = trained.plantgen[["unique_id", "county_fips"]].copy()
    crowding = plantgen.groupby("county_fips")["unique_id"].transform("size")
    plantgen["county_crowding"] = crowding.map(lambda n: "shared county" if n > 1 else "alone")

    best_right = best_per_record(predictions, "plantgen")[
        ["unique_id_r", "match_probability", "match_weight"]
    ].rename(columns={"unique_id_r": "unique_id"})
    merged = plantgen.merge(best_right, on="unique_id", how="left")
    merged["match_probability"] = merged["match_probability"].fillna(0.0)

    by_crowding = (
        merged.groupby("county_crowding")["match_probability"]
        .agg(
            plants="size",
            median="median",
            p75=lambda s: s.quantile(0.75),
            p90=lambda s: s.quantile(0.9),
            max="max",
            above_0_5=lambda s: int((s > 0.5).sum()),
            above_0_9=lambda s: int((s > 0.9).sum()),
        )
        .reset_index()
    )

    watched = _watched_county_report(merged, trained.plantgen)

    # Canada: 8 GSPT plants whose counterpart cannot exist. Kept in the denominator on
    # purpose -- filtering them out would shrink it and make the match rate look better
    # than it is.
    canadian_ids = sorted(trained.gspt.loc[trained.gspt["country_area"] == "Canada", "unique_id"])
    pair_counts = predictions["unique_id_l"].value_counts()
    best_left = best_per_record(predictions, "gspt").set_index("unique_id_l")
    canada = pd.DataFrame(
        [
            {
                "unique_id_l": plant,
                "candidate_pairs": int(pair_counts.get(plant, 0)),
                # "never compared" and "compared and rejected" are different outcomes and
                # must not both be printed as a probability of zero.
                "outcome": "never compared"
                if pair_counts.get(plant, 0) == 0
                else "compared, best below threshold",
                "best_match_probability": float(
                    best_left.loc[plant, "match_probability"] if plant in best_left.index else 0.0
                ),
            }
            for plant in canadian_ids
        ]
    )

    report = ResolutionReport(
        blocking=blocking_report(trained),
        comparators=comparator_report(trained),
        histogram=probability_histogram(predictions),
        overall_quantiles=_quantiles(predictions["match_probability"]),
        by_county_crowding=by_crowding,
        watched_counties=watched,
        canada=canada,
        em_sessions=trained.em_sessions,
        em_failures=trained.em_failures,
    )

    if write:
        keep = [
            c
            for c in (
                "unique_id_l",
                "unique_id_r",
                "match_probability",
                "match_weight",
                "gamma_zip5",
                "gamma_street",
                "gamma_place",
                "gamma_alias_place",
                "gamma_start_year",
                "gamma_county",
            )
            if c in predictions.columns
        ]
        write_table(
            RESOLUTION_NAMESPACE,
            MATCH_TABLE,
            pa.Table.from_pandas(predictions[keep], preserve_index=False),
            db_path=db_path,
            warehouse=warehouse,
        )
    return trained, report


def main(argv: list[str] | None = None) -> int:
    import argparse
    import logging

    parser = argparse.ArgumentParser(description="Train the linker and report on it.")
    parser.add_argument("--no-write", action="store_true", help="Skip writing the Iceberg table.")
    args = parser.parse_args(argv)
    logging.getLogger("splink").setLevel(logging.ERROR)
    _, report = build(write=not args.no_write)
    print(report.render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
